apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
  labels:
    app: {{ .Release.Name }}-db-service
spec:
  type: NodePort
  ports:
  - port: 5432
    name: database-port
  selector:
    app: {{ .Release.Name }}-db-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db-statefulset
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db-statefulset
  serviceName: {{ .Release.Name }}-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: postgres-database-data
        hostPath:
          path: {{ .Values.deployments.databasePath }}
          type: DirectoryOrCreate
      containers:
      - name: postgres-sql
        image: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: {{ .Values.deployments.databaseName }}
        ports:
        - containerPort: 5432
          name: database-port
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-database-data